# Generated by Django 4.1.4 on 2023-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchNumber', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('RoundNumber', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('DateUtc', models.DateTimeField()),
                ('Location', models.CharField(max_length=100)),
                ('HomeTeam', models.CharField(max_length=100)),
                ('AwayTeam', models.CharField(max_length=100)),
                ('Group', models.CharField(blank=True, max_length=100, null=True)),
                ('HomeTeamScore', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('AwayTeamScore', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
