# Generated by Django 4.1.4 on 2022-12-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(choices=[('Fi', '1'), ('Se', '2'), ('Th', '3'), ('Fo', '4'), ('Fv', '5')], default='Fi', max_length=2)),
                ('financing', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('Fi', '1'), ('Se', '2'), ('Th', '3'), ('Fo', '4'), ('Fv', '5')], default='Fi', max_length=2)),
                ('departamentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('Ze', '0'), ('Fi', '1'), ('Se', '2'), ('Th', '3'), ('Fo', '4'), ('Fv', '5')], default='Ze', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=100, unique=True)),
                ('IsProfessor', models.BooleanField(default=False)),
                ('salary', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subjectId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.subjects')),
                ('teacherId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.groups')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsLectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curatorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.curators')),
                ('groupId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.groups')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsCurators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curatorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.curators')),
                ('groupId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.groups')),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='facultyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='third_app.faculties'),
        ),
    ]
