# Generated by Django 4.1.4 on 2023-01-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0004_subscription_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='starttime',
        ),
        migrations.CreateModel(
            name='TrainWithTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('nameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fourth_app.trainer')),
            ],
        ),
    ]
