# Generated by Django 4.1.4 on 2023-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0005_remove_trainer_endtime_remove_trainer_starttime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveBigIntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
