# Generated by Django 4.1.4 on 2023-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='day', max_length=100),
        ),
    ]
