# Generated by Django 4.1.4 on 2023-01-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0008_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='DayOfWeek',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
