# Generated by Django 4.1.4 on 2023-01-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0009_remove_subscription_dayofweek_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='userid',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
