# Generated by Django 4.1.4 on 2023-01-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0012_remove_order_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subid',
        ),
        migrations.AddField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fourth_app.products'),
        ),
    ]
