# Generated by Django 4.1.4 on 2022-12-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_fruits_and_vegetables_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits_and_vegetables',
            name='type',
        ),
    ]
