# Generated by Django 4.1.4 on 2022-12-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_fruits_and_vegetables_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits_and_vegetables',
            old_name='category',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='fruits_and_vegetables',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
