# Generated by Django 4.1.4 on 2023-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0003_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('wallet', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
    ]
