# Generated by Django 4.1.4 on 2023-01-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0007_alter_wallet_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet',
            new_name='balance',
        ),
    ]
