# Generated by Django 4.1.4 on 2023-01-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0008_rename_wallet_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='userid',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
