# Generated by Django 4.1.4 on 2023-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0012_gym_subscription_trainer_trainwithtrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
