# Generated by Django 4.1.4 on 2023-01-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0013_testtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtime',
            old_name='time',
            new_name='geeks_field',
        ),
    ]
