# Generated by Django 4.1.4 on 2023-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0016_alter_testtime_geeks_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtime',
            name='geeks_field',
            field=models.DateField(),
        ),
    ]
