# Generated by Django 4.1.4 on 2023-01-18 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0017_alter_testtime_geeks_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTime',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='geeks_field',
            field=models.DateField(default=datetime.date(2023, 1, 18)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='userid',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
