# Generated by Django 4.1.4 on 2023-01-18 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0019_remove_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_time',
            field=models.DateField(default=datetime.date(2023, 1, 18)),
        ),
    ]
