# Generated by Django 4.1.4 on 2023-01-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0020_subscription_end_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
