# Generated by Django 4.1.4 on 2023-01-19 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0022_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_time',
            field=models.DateField(default=datetime.date(2023, 1, 19)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='geeks_field',
            field=models.DateField(default=datetime.date(2023, 1, 19)),
        ),
    ]
