# Generated by Django 4.1.4 on 2023-01-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0023_alter_subscription_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='userid',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
