# Generated by Django 4.1.4 on 2023-01-20 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0027_alter_gym_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainwithtrainer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_time',
            field=models.DateField(default=datetime.date(2023, 1, 20)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='geeks_field',
            field=models.DateField(default=datetime.date(2023, 1, 20)),
        ),
    ]
