# Generated by Django 4.1.4 on 2023-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0028_trainwithtrainer_price_alter_subscription_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainwithtrainer',
            name='nameid',
        ),
        migrations.AddField(
            model_name='trainwithtrainer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
