# Generated by Django 4.1.4 on 2023-01-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0030_autoregister_justuser_alter_subscription_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyorus', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='justuser',
            name='companyORuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiveth_app.companyoruser'),
        ),
    ]
