# Generated by Django 4.1.4 on 2023-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0031_companyoruser_alter_justuser_companyoruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justuser',
            name='companyORuser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CompanyOrUser',
        ),
    ]
