# Generated by Django 4.1.4 on 2023-04-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0033_categoryforwashing_delete_gym_delete_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryforwashing',
            name='description',
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('nameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiveth_app.categoryforwashing')),
            ],
        ),
    ]
