# Generated by Django 4.1.4 on 2023-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0034_remove_categoryforwashing_description_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryforwashing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
