# Generated by Django 4.1.4 on 2023-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0035_categoryforwashing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='timewashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('userid', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
    ]
