# Generated by Django 4.1.4 on 2023-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0036_timewashing'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewashing',
            name='journey_length',
            field=models.DurationField(null=True),
        ),
    ]
