# Generated by Django 4.1.4 on 2023-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0037_timewashing_journey_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewashing',
            name='journey_length',
        ),
    ]
