# Generated by Django 4.1.4 on 2023-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0038_remove_timewashing_journey_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewashing',
            name='userid',
            field=models.PositiveBigIntegerField(),
        ),
    ]
