# Generated by Django 4.1.4 on 2023-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0039_alter_timewashing_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewashing',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timewashing',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
