# Generated by Django 4.1.4 on 2023-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0041_remove_timewashing_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timewashing',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timewashing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=10),
        ),
    ]
