# Generated by Django 4.1.4 on 2023-04-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0044_delete_timewashingcompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timewashing',
            name='company_or_user',
        ),
    ]
