# Generated by Django 4.1.4 on 2023-04-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0045_remove_timewashing_company_or_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoregister',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
