# Generated by Django 4.1.4 on 2023-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveth_app', '0046_autoregister_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoregister',
            name='userid',
            field=models.PositiveBigIntegerField(),
        ),
    ]
