# Generated by Django 4.1.4 on 2022-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=13)),
                ('salary', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
    ]
