# Generated by Django 4.1.4 on 2022-12-12 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayOfWeek', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(7)])),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)])),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
