# Generated by Django 4.1.4 on 2022-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_examinations_wards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinations',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examinations',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
