# Generated by Django 4.1.4 on 2022-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_alter_examinations_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinations',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examinations',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
