# Generated by Django 4.1.4 on 2022-12-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0006_alter_examinations_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinations',
            name='DayOfWeek',
        ),
    ]
