# Generated by Django 4.1.4 on 2022-12-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0007_remove_examinations_dayofweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinations',
            name='DayOfWeek',
            field=models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], default='Mo', max_length=2),
        ),
    ]
