# Generated by Django 4.1.4 on 2022-12-14 08:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0008_examinations_dayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsExaminations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinLengthValidator(Decimal('0.00'))])),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Diseases',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='financing',
        ),
        migrations.RemoveField(
            model_name='examinations',
            name='DayOfWeek',
        ),
        migrations.RemoveField(
            model_name='examinations',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='examinations',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='wards',
            name='building',
        ),
        migrations.RemoveField(
            model_name='wards',
            name='floor',
        ),
        migrations.AddField(
            model_name='doctors',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='wards',
            name='departamentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.departments'),
        ),
        migrations.AddField(
            model_name='wards',
            name='places',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='departments',
            name='building',
            field=models.CharField(choices=[('Fi', '1'), ('Se', '2'), ('Th', '3'), ('Fo', '4'), ('Fv', '5')], default='Fi', max_length=2),
        ),
        migrations.AddField(
            model_name='donation',
            name='departamentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.departments'),
        ),
        migrations.AddField(
            model_name='donation',
            name='sponsorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.sponsors'),
        ),
        migrations.AddField(
            model_name='doctorsexaminations',
            name='doctorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.doctors'),
        ),
        migrations.AddField(
            model_name='doctorsexaminations',
            name='examinationod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.examinations'),
        ),
        migrations.AddField(
            model_name='doctorsexaminations',
            name='wardid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.wards'),
        ),
    ]
